global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

# Alert configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Rule files to load
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'network_monitor'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:8000']
        labels:
          instance: 'network_metrics'
          service: 'network_monitoring'

  - job_name: 'haproxy'
    scrape_interval: 5s
    metrics_path: /stats;csv
    static_configs:
      - targets: ['localhost:8404']
        labels:
          instance: 'haproxy'
          service: 'load_balancer'

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
        labels:
          instance: 'prometheus'
          service: 'monitoring'